### PR TITLE
This commit adds formatting and links to log output

### PR DESCRIPTION
**Pull request by brownjohnf**
When running pharos with many older, unresponded-to threads, it's hard
to find the threads that are triggering the notifications. This PR adds
a permalink to the convo to the log output so you can go back and find
them.

I also cleaned up the Dockerfile a bit and extended the .gitignore.

### CODE REVIEW

**Comment by brownjohnf** [comment]
@craig-mulligan ^^

**Comment by craigmulligan** [comment]
Nice! looks good to me.

**Comment by brownjohnf** [comment]
Cool. I don't have write access to the repo, so you'll need to merge.

**Comment by brownjohnf** [comment]
@craig-mulligan ping on merging, if you like this.

**Comment by craigmulligan** [comment]
missed this, my B.

**Pull request merged**
